###get all products
GET http://localhost:3000/productApi/products

###create product 
POST http://localhost:3000/productApi/products
Content-Type: application/json

{
    "productName":"glass",
    "price":1208,
    "brand":"pvc"
}

###create user
POST http://localhost:3000/userApi/user
Content-Type: application/json

{
    "name":"manaswi",
    "email":"manaswi12@gmail.com",
    "password":"hi",
    "cart":[]
}

###add product to cart
PUT http://localhost:3000/userApi/user-cart/user-id/69819092c04f7f1be02869e9/product-id/69819078c04f7f1be02869e4



###read user by id
GET http://localhost:3000/userApi/user/698181b86ffbf7b67ce38d80

