GET http://localhost:3000/user-api/users

###
POST http://localhost:3000/user-api/users
Content-Type: application/json

{
    "id":201,
    "name":"lokesh",
    "age":22
}

###
PUT http://localhost:3000/user-api/users/201
Content-Type: application/json

{
    "id":201,
    "name":"lokesh yadav",
    "age":23
}


###read a user by id
GET http://localhost:3000/user-api/users/201


###
DELETE http://localhost:3000/user-api/users/201






###read all products
GET http://localhost:3000/product-api/products

###read products by id
GET http://localhost:3000/product-api/products-id/100

###read products by name
GET http://localhost:3000/product-api/products-name/glass

###push new products
POST http://localhost:3000/product-api/products
Content-Type: application/json

{
    "productId":100,
    "name":"glass",
    "price":1200,
    "brand":"LG"
}


###edit products
PUT http://localhost:3000/product-api/products/100
Content-Type:application/json

{
    "productId":100,
    "name":"TV",
    "price":10200,
    "brand":"LG"
}


###delete products
DELETE  http://localhost:3000/product-api/products/100